### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by atilaromero**
A Dockerfile for Skyperyous.

How to use:

```
docker build . -t skyperious
xhost +
docker run --rm -it -e DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix/ skyperious
```

### CODE REVIEW

**Comment by suurjaak** [comment]
Pardon me, I somehow completely overlooked this PR. 

Can you explain the purpose of it? Docker is not exactly geared towards running GUI applications. Is it to avoid installing wx to system libs?

**Comment by atilaromero** [comment]
There are many GUI applications you can run using docker: https://github.com/jessfraz/dockerfiles
My main use case in particular is to avoid installing dependencies, so I can test a program without changes to my system. I'm not worried about any particular lib, but I have the habit of using software inside containers. One good consequence of this is that you can tell people how to run an application by pointing them to how to launch the docker container. This avoids those "it works on your system but not in mine" kind of situations.

If you feel that this is not the right path for your project, that's ok too. I just thought I should share what I did in case it could be useful.

**Comment by suurjaak** [comment]
Sounds reasonable. Users have already provided a Vagrantfile for Skyperious, so why not a Dockerfile, it's more common anyway.

**Comment by suurjaak** [comment]
FYI: I could not get wxPython installed with this Dockerfile. Had to fall back to using one of the prepared wheels from https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04.

**Pull request merged**
