### PR TITLE
Added filter links to date headers

### PR DESCRIPTION
**Pull request by miloush**
Click a date header in a chat log to change the filter to that date.

### CODE REVIEW

**Comment by suurjaak** [comment]
Sorry for not dealing with this PR before. 

Currently this change does not do what it advertises - simply adding a position to datelinks does nothing if there is no actual link involved. 

What is the intended purpose here?

**Comment by miloush** [comment]
I am not sure I understand "if there is no actual link involved". It turns the date into a link and works the way I intended, i.e. when you click on a date in the chat log, the log is filtered by that date.

**Comment by suurjaak** [comment]
Pardon me, indeed it does, I overlooked one line. 

But what is the intended purpose? Why would a user want to filter a chat by the day they're already seeing?

**Comment by miloush** [comment]
The user scenario is you search for a phrase, i.e. use the "Find messages with text", you locate the message you are looking for in the chat log and then you want to see the context - messages before and after. With this PR, you click on the date and have to clear the text filter (I didn't see a trivial way how to do that with the link itself).

Typically you would be looking for something you don't know, for example a phone number or url, but you know the reference that you can search for such as "ophthalmologist". Then you have to see the rest of the messages to get the number you are looking for.

This was the minimal code change I could come up with that makes the process significantly easier, but I am open to different solutions.

**Comment by suurjaak** [comment]
Aha. In this context, the use case does make sense. 

But I don't know if it's a good idea to turn all date headers into such auto-filter links. It's quite unexpected behaviour, and it's not easy to restore the previous view. I will ruminate on this. 

Maybe an option in the context menu when right-clicking on a message, will suffice? 

FYI: you can also search for a phrase within the current message list via the search bar (the magnifier icon in the bottom right corner).

**Comment by miloush** [comment]
> search for a phrase within the current message list via the search bar

The top three conversations in my case have 200-250k messages each, loading them all takes forever and you want to see the results next to each other, not scrolling through such amount.

> option in the context menu when right-clicking on a message, will suffice?

Absolutely! I don't insist on the date headers.

**Comment by suurjaak** [comment]
I will add the menu feature to dev queue. 

Closing this PR, then.

**Pull request closed without merging**
